// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Retrieves a user by their unique identifier.
	GetUserById(ctx context.Context, id string) (User, error)
	// Retrieves a user by their unique username.
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
