// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signing_keys.sql

package db

import (
	"context"
)

const activateSigningKey = `-- name: ActivateSigningKey :execrows
UPDATE signing_keys SET is_active = true WHERE kid = $1
`

func (q *Queries) ActivateSigningKey(ctx context.Context, kid string) (int64, error) {
	result, err := q.db.Exec(ctx, activateSigningKey, kid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateAllSigningKeys = `-- name: DeactivateAllSigningKeys :exec
UPDATE signing_keys SET is_active = false WHERE is_active
`

func (q *Queries) DeactivateAllSigningKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllSigningKeys)
	return err
}

const deleteSigningKey = `-- name: DeleteSigningKey :exec
DELETE FROM signing_keys WHERE kid = $1
`

func (q *Queries) DeleteSigningKey(ctx context.Context, kid string) error {
	_, err := q.db.Exec(ctx, deleteSigningKey, kid)
	return err
}

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT kid, public_pem, private_enc, is_active, created_at
FROM signing_keys
WHERE is_active
`

func (q *Queries) GetActiveSigningKey(ctx context.Context) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.PublicPem,
		&i.PrivateEnc,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertSigningKey = `-- name: InsertSigningKey :one
INSERT INTO signing_keys (kid, public_pem, private_enc, is_active)
VALUES ($1, $2, $3, $4)
RETURNING kid, public_pem, private_enc, is_active, created_at
`

type InsertSigningKeyParams struct {
	Kid        string `json:"kid"`
	PublicPem  string `json:"public_pem"`
	PrivateEnc []byte `json:"private_enc"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, insertSigningKey,
		arg.Kid,
		arg.PublicPem,
		arg.PrivateEnc,
		arg.IsActive,
	)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.PublicPem,
		&i.PrivateEnc,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listSigningKeys = `-- name: ListSigningKeys :many
SELECT kid, public_pem, private_enc, is_active, created_at
FROM signing_keys
ORDER BY is_active DESC, created_at DESC
`

// All signing keys, active first. Feeds the in-memory cache and JWKS.
func (q *Queries) ListSigningKeys(ctx context.Context) ([]SigningKey, error) {
	rows, err := q.db.Query(ctx, listSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningKey
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.Kid,
			&i.PublicPem,
			&i.PrivateEnc,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
